### ISSUE TITLE
Add a container view instead of an image view

### ISSUE THREAD

**Issue by Mattporter0** [MichMich/ParallaxTableView#1]
Is it possible to add a container view with this? I need to use one as I'm using a sliding image view library from github that needs to be indebted into a container view with its custom class.

Any ideas? Would be a big help!

Matt

**Comment by MichMich** [comment]
Yes, that is pretty simple. 

In the ParallaxTableViewController.swift, replace the following line:

```
let imageView = UIImageView()
```

with:

```
let imageView = UIView()
```

This should be enough. But of course, your containerview would be called imageView, which isn't very  clean. All you have to do is rename all the occurrences of the word `image` into `container` (or any other arbitrary word).

Let me know if this helps.
